name: Accuracy Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled

jobs:
  run-accuracy-tests:
    name: Run Accuracy Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'accuracy-tests')
    env:
      MDB_OPEN_AI_API_KEY: ${{ secrets.ACCURACY_OPEN_AI_API_KEY }}
      MDB_GEMINI_API_KEY: ${{ secrets.ACCURACY_GEMINI_API_KEY }}
      MDB_AZURE_OPEN_AI_API_KEY: ${{ secrets.ACCURACY_AZURE_OPEN_AI_API_KEY }}
      MDB_AZURE_OPEN_AI_API_URL: ${{ vars.ACCURACY_AZURE_OPEN_AI_API_URL_V2 }}
      MDB_ACCURACY_MDB_URL: ${{ secrets.ACCURACY_MDB_CONNECTION_STRING }}
      MDB_ACCURACY_MDB_DB: ${{ vars.ACCURACY_MDB_DB }}
      MDB_ACCURACY_MDB_COLLECTION: ${{ vars.ACCURACY_MDB_COLLECTION }}
      MDB_ACCURACY_BASELINE_COMMIT: ${{ github.event.pull_request.base.sha || '' }}

      MDB_API_CLIENT_ID: ${{ secrets.TEST_ATLAS_CLIENT_ID }}
      MDB_API_CLIENT_SECRET: ${{ secrets.TEST_ATLAS_CLIENT_SECRET }}
      MDB_VOYAGE_API_KEY: ${{ secrets.TEST_MDB_MCP_VOYAGE_API_KEY }}
      MDB_MONGOT_PASSWORD: ${{ secrets.TEST_MDB_MONGOT_PASSWORD }}

    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run accuracy tests
        run: pnpm run test:accuracy
      - name: Upload accuracy test summary
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: accuracy-test-summary
          path: .accuracy/test-summary.html
      - name: Comment summary on PR
        if: github.event_name == 'pull_request' && github.event.label.name == 'accuracy-tests'
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
        with:
          # Hides the previous comment and add a comment at the end
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          path: .accuracy/test-brief.md
